server:
  port: 8081
spring:
  application:
    name: fubaodai
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    publisherConfirms: true
